### ISSUE TITLE
error : invalid central directory file header signature: 0x5053884e

### ISSUE THREAD

**Issue by mouradsamyroushdy** [thejoshwolfe/yauzl#116]
I'm using [pdftron/webviewer-downloader](https://www.npmjs.com/package/@pdftron/webviewer) which has a dependency [extract-zip](https://github.com/maxogden/extract-zip) which in turn uses 
[yauzl](https://www.npmjs.com/package/yauzl)

**Node version:** v10.19.0
**Development (Local):** working fine and no problems at all.
**Production (Azure Pipeline):** causes this error:
> EXEC : error : invalid central directory file header signature: 0x5053884e

![Capture](https://user-images.githubusercontent.com/13928054/76213712-ee4ac680-6213-11ea-9ec6-85aaf660462b.png)

**Comment by thejoshwolfe** [comment]
Is your problem already covered here: https://github.com/thejoshwolfe/yauzl/issues?q=%22invalid+central+directory+file+header+signature%22 ?
