### ISSUE TITLE
Unable to open correct Zip64 files with 0xffff as "number of this disk" in eocdr

### ISSUE THREAD

**Issue by rossj** [thejoshwolfe/yauzl#120]
Yauzl currently throws an error when opening some valid single disk / volume Zip64 files due to the "number of this disk" check not considering the Zip64 override value. For example, I have files with 0xffff as the "number of this disk" value in the standard eocdr, with an override value of 0 in the zip64 eocdr, which currently error with yauzl.

These files seem correct, as APPNOTE.TXT states the following for the "number of this disk" field:
```
If an archive is in ZIP64 format
and the value in this field is 0xFFFF, the size will 
be in the corresponding 4 byte zip64 end of central 
directory field.
```

Proposed fix in https://github.com/thejoshwolfe/yauzl/pull/118

**Comment by thejoshwolfe** [comment]
This should be fixed in yauzl version 3.1.1
