### ISSUE TITLE
[Feature Request] Support for AES-256 decryption

### ISSUE THREAD

**Issue by papb** [thejoshwolfe/yauzl#121]
It would be awesome to see support for AES-256 decryption in yauzl. This would be the last thing I need before I can completely stop calling 7zip via [execa](https://github.com/sindresorhus/execa), and solve all my zipping needs in pure Node.

I have zero knowledge on how to implement this, is this very hard to implement?

Thank you very much for this library!!

I have also opened a mirror issue for yauzl: https://github.com/thejoshwolfe/yazl/issues/62

**Comment by thejoshwolfe** [comment]
Crypto support is not planned. I'm not enthusiastic enough to do my own research on how it works in real world use cases.
