### ISSUE TITLE
Opening of archive with entry named "/" fails

### ISSUE THREAD

**Issue by erikjalevik** [thejoshwolfe/yauzl#135]
I've just got yauzl up and running and it works great on most zip files, but I have one where it fails immediately after calling `yauzl.open` with the error "absolute path: /".

It appears that this archive contains a directory entry with just `/` as its path. Once yauzl hits this, it throws an error and stops.

If I edit the yauzl source code to not call `validateFileName`, it extracts it just fine. Finder doesn't have any issues extracting this file either. Is there a way to disable validating file names without switching off `decodeStrings`?

Happy to forward you the file for debugging if needed.

**Comment by jusjusjus** [comment]
That's actually a feature.  If absolute paths were allowed, a user might try to inject data into the server into areas where she shouldn't.  I found (maybe by accident) that symlinks are also save with this library.

**Comment by erikjalevik** [comment]
Yes, I agree it's a sensible thing to do.

In my case though, I'm using this as part of a desktop Electron app, where I filter out all directory names and then concatenate the relative filename inside the zip with the path to the output folder.

In the end, I just ended up setting `decodeStrings` to false, and converting the filename manually. Now it all runs smoothly.

**Comment by thejoshwolfe** [comment]
The recommendation if you need to support invalid and unsafe file names in an archive is to do what you did, set `decodeStrings` to false. The additional hassle of decoding the bytes to a string isn't exactly intentional, but it does make the safe and standard thing to do much more convenient, which seems like the right design to me.
