### ISSUE TITLE
Invalid signature causes process to close unexpectedly

### ISSUE THREAD

**Issue by Portur** [thejoshwolfe/yauzl#136]
Hi,

When unzipping a file (~40kb) I get a signature error (`Uncaught Error: invalid central directory file header signature: 0xbfef2b1c`) and the process immediately stops and ends nodejs.

I noticed the error emitted in [emitErrorAndAutoClose](https://github.com/thejoshwolfe/yauzl/blob/96f0eb552c560632a754ae0e1701a7edacbda389/index.js#L225)

Below is how I use it. You'll notice the `try/catch` is ignored (?)
```js
        let yauzl = require("yauzl");
        try {

            yauzl.open(file_path, {lazyEntries: true}, function (err, zipfile) {
                if (err)
                    reject('Could not unzip > ' + err);
                else {
                    zipfile.readEntry();
                    zipfile.on("entry", function (entry) {
                        if (entry.fileName === 'doc.kml') {
                            // stuff
                        }
                        else {
                            zipfile.readEntry();
                        }
                    });
                }
            });
        }
        catch (e) {
            reject(e)
        }
```

Here is the stack
![image](https://user-images.githubusercontent.com/24350810/98923668-a257cc00-24dc-11eb-895c-ee654922f55a.png)

Not sure f it makes a difference but this specific file has made it rounds through various email clients. 
Also this is a `kmz`, which is a zipped `kml` which is sugar for zipped `xml`.  

Here it is 
https://storage.googleapis.com/coverage-hosting-public/Clear%20Access%20FTTH%20August%202020.kmz

**Comment by Portur** [comment]
More digging, it seems the file is actually opened and is `uncaught`.

The problem is there are no events created for `error`
```js

                    zipfile.on("close", function() {
                        console.log("closed yauzl read");
                    });
                    zipfile.on("error", function(e) {
                        console.log("error yauzl read");
                    })
```

With those created I catch the error successfully. Could I recommend that in a case where the user forgets to add those listeners, could you perhaps `throw` rather than shutdown

**Comment by thejoshwolfe** [comment]
there is a section of the docs that explains how to avoid crashing the process.
