### ISSUE TITLE
use bigint

### ISSUE THREAD

**Issue by jimmywarting** [thejoshwolfe/yauzl#139]
haven't looked into any issues or the code - just discovered this package

but i read this:

> Limitted ZIP64 Support
For ZIP64, only zip files smaller than 8PiB are supported, not the full 16EiB range that a 64-bit integer should be able to index. This is due to the JavaScript Number type being an IEEE 754 double precision float.

> The Node.js fs module probably has this same limitation.

you should be using BigInts to handle large numbers (and plz no bn.js or other polyfill - just use native bigints instead)

**Comment by thejoshwolfe** [comment]
Nah.
