### ISSUE TITLE
Unzipping nested folders from archive

### ISSUE THREAD

**Issue by konradgodel** [thejoshwolfe/yauzl#140]
I made a [stackoverflow post here](https://stackoverflow.com/questions/69665329/zip-archive-with-nested-folder-inside-does-not-unzip-with-yauzl) to describe the situation, but thought it would be best to share here to get an answer.

TLDR is, I need to unzip archives while keeping the subfolders, is that possible with yauzl?

**Comment by thejoshwolfe** [comment]
looks like you got an answer. The short answer to your question is: yes that's possible. yauzl doesn't extract anything to disk; that's up to you to do, so preserving subfolder structure is definitely within your power to accomplish.
