### ISSUE TITLE
What file types are supported?

### ISSUE THREAD

**Issue by ajmeese7** [thejoshwolfe/yauzl#142]
Hello there, I'm looking for a list of the supported file types that this library can extract from. Obviously `zip` files are supported, but how about the following:

- `7z`
- `ar`
- `bz2`
- `gz`
- `lz`
- `lzh`
- `rar`
- `tar`
- `zst`

I am looking to combine this with the `file-type` library and those are all the archive types that can be detected by the library, so I just want to ensure that my code covers all of the overlap between your library and their file types.

Thanks in advance!

**Comment by thejoshwolfe** [comment]
yauzl supports the zip file format as specified by PKWARE's APPNOTE.TXT . I only recognize some of the file extensions you listed, but I believe yauzl supports none of them. Certain file formats are zip files by another name, such as `jar`, `apk`, and sometimes `exe`, but yauzl doesn't operate on file extensions at all; it's lower level than that.

Determining if a file is a zipfile can be accomplished by opening the file with yauzl and checking for an immediate error or not. Note that files can be multiple types at once, like exe and zip.
