### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open xxx file path

### ISSUE THREAD

**Issue by x-fox** [thejoshwolfe/yauzl#144]
Try to unzip a zip file, file size approximately 800M, got an error: 
![40127de2d2e741eda8517b83c481643](https://user-images.githubusercontent.com/12230411/235139360-9ec905ea-9f64-415b-ae00-d031aeb2647f.png)

**Comment by thejoshwolfe** [comment]
This is not an error from yauzl.
