### ISSUE TITLE
streaming unzip?

### ISSUE THREAD

**Issue by maxogden** [thejoshwolfe/yauzl#15]
I just wanted to see if you guys thought about supporting a pure unzip use case, e.g.

```
cat file.zip | unzip
```

It seems thats the approach taken by `node-unzip`: https://github.com/EvanOxfeld/node-unzip/blob/5a62ecbcef6523708bb8b37decaf6e41728ac7fc/lib/parse.js#L51-L57

They basically scan through the zip beginning -> and and when they see different signatures they emit entries, whereas the yauzl approach is to first skip to the end and read the CDR and emit entries from that.

The nice thing about a pure stream API is you can use unix pipes and not require random access in order to unzip. On the other hand, the nice thing about reading the CDR first is you can do e.g. lazy file mounting + extracting use cases over HTTP like I did in the issue yesterday.

I'm just curious if there are other reasons why streaming unzipping isn't implemented in yauzl other than its currently a nice compact 400 line implementation and supporting two APIs would be tedious. Cheers :)

**Comment by andrewrk** [comment]
See #12

**Comment by maxogden** [comment]
@andrewrk ahh that makes tons of sense! IMO that info should be in the readme :)

**Comment by andrewrk** [comment]
This text is supposed to be it:

> Follow the spec. Don't scan for local file headers. Read the central directory for file metadata.

But I agree, a bold headline FAQ entry style thing would be appropriate here.

**Comment by andrewrk** [comment]
oh, also this part: https://github.com/thejoshwolfe/yauzl#local-file-headers-are-ignored
