### ISSUE TITLE
Provide an option to ignore Info-ZIP Unicode Path Extra Field

### ISSUE THREAD

**Issue by sandy081** [thejoshwolfe/yauzl#159]
VS Code uses yazl & yauzl packages for zipping and unzipping extensions respectively. We do not use any extra headers while creating the zip, therefore we do not want to respect these extra headers while unzipping. 

But there is no option in yauzl package to skip these headers. It would be great if you can provide an option to skip.

**Comment by thejoshwolfe** [comment]
A VS Code developer. Hello! I use your software every day at work. Thanks for your open source contributions! I'm happy to hear yazl and yauzl are useful for you.

It sounds like you're encountering zip files that include the Info-ZIP Unicode Path Extra Field, but you would like to ignore the extension override and use the regular file name instead (and presumably interpret it as UTF-8?). I'm very interested in how this situation came to be. Do you know which software created these zip files? Was it a buggy version of the software? What's the reason you want to ignore the file name in the extension data?

In #33, a zipfile was provided (unknown where it came from) that presumably used CP936 for the regular file name, and the Info-ZIP Unicode Path Extra Field was required to figure out the correct interpretation of the names. In the example zip file provided in that issue, General Purpose Bit 11 `Language encoding flag (EFS)` was not set, which according to the spec means that the filename is encoded in CP437, which is definitely wrong. The extension was required to interpret the file name correctly in that case. See also #84, which is also related to file name encoding.

If we can figure out exactly why we need a skip option, I would like to document that as justification, like how the README today about backslash normalization references a bug in ".NET versions 4.5.0 until 4.6.1".

**Comment by sandy081** [comment]
@thejoshwolfe Glad that you use VS Code 🎉 

Our extension packaging software, [VSCE](http://github.com/microsoft/vscode-vsce), uses `yazl` library to package the extension. I believe this library does not support `Info-ZIP Unicode Path Extra Field` header and therefore we want to be consistent and not support this header while unzipping.

**Comment by thejoshwolfe** [comment]
Oh interesting. I'm not sure I understand the intent. The `Info-ZIP Unicode Path Extra Field` is an official extension listed in the spec: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT . So if the intent is to support reading standard-compliant zipfiles, I recommend allowing the extra field. If the intent is to only support zipfiles created specifically by `yazl`, that would be a challenging usecase to support. Do you want to reject otherwise compliant zip files in some cases?

Or maybe a different question would be: have you found a zipfile where recognizing the extra field causes a significant difference? and do you know what software created that zip file?

If the desire is just for consistency, I recommend instead focusing on standard-compliant behavior. I think that will give better results, but I'm curious if you've found a counterexample.

**Comment by sandy081** [comment]
Our intent is more about being precautious, rather than being consistent. While `vsce` does use `yazl` to package up extensions, where the ZIP feature set is kept under control, an extension can be crafted using other tools and thus use any ZIP format feature, including the `Info-ZIP Unicode Path Extra Field`. We'd like to limit the use of such features and the best idea we've come up with was to do it at extraction time. We understand this would be an option which most of your customers would simply ignore.

We're willing to contribute with a PR, let us know if you'd be up for it.

**Comment by sandy081** [comment]
Thanks for the detailed explanation — your approach to handling various ZIP quirks is much appreciated.

Apologies for the delayed response. After giving this another look and reevaluating how we handle ZIP processing in the context of VSIX (the format used for VS Code extensions), I wanted to follow up with a bit more context and a proposal.

We’re working with VSIX files, which are ZIP-based but follow a custom convention for packaging Visual Studio Code extensions. While they technically use the ZIP format, they aren’t expected to be fully compatible with all ZIP features — including the Info-ZIP Unicode Path Extra Field.

We’d like to request support for an option in yauzl to ignore this specific extra field during unzip operations. Supporting it introduces complexity in our toolchain, and since VSIX is a controlled format, we’ve chosen not to support or rely on this header across our ecosystem — including the extension publishing pipeline and the VS Code client.

We understand this may not align fully with ZIP spec compliance, but for our use case, consistency and simplicity across tooling outweigh the need to interpret this field correctly. Would you consider adding a flag (or some mechanism) to opt out of parsing this extra field?

If you’re open to it, I’d be happy to contribute a PR to implement this behavior.

Thanks again, and I’d appreciate your thoughts.

**Comment by sandy081** [comment]
I think this should work.
