### ISSUE TITLE
No Streaming (Question / Brain storming)

### ISSUE THREAD

**Issue by nmccready** [thejoshwolfe/yauzl#16]
>No Streaming Unzip API
>
>Due to the design of the .zip file format, it's impossible to interpret a .zip file from start to finish (such as >from a readable stream) without sacrificing correctness. The Central Directory, which is the authority on >the contents of the .zip file, is at the end of a .zip file, not the beginning.

I really don't know jack about the zip format, but I am just trying to think out of the box here for possibly having a streaming api. 

Since the CD is at the end can we not read the file stream in reverse? Thus then detect the CD. 

The main use case I am looking is for getting a single large file out of many in a zip using streaming if possible.

**Comment by andrewrk** [comment]
It sounds like you are misunderstanding what "no streaming" means. When you extract a file from a zip file, you extract it as a stream, as expected. But the zip file itself must not be a stream; it must be a file on disk or in memory, or as in #14, some other sort of random access data.

**Comment by nmccready** [comment]
No I get that part. I plan on getting the zip file via ftp as a stream. But I only need one file out of that zip of  many.

**Comment by andrewrk** [comment]
If #14 is solved you could implement an interface to FTP which supports ranged reads, and then solve it that way.

**Comment by nmccready** [comment]
Yes this is on point with what I was thinking as well. I guess I'll close this issue and follow the one above.
