### ISSUE TITLE
Comments are CP437?

### ISSUE THREAD

**Issue by kirkouimet** [thejoshwolfe/yauzl#19]
Hey @thejoshwolfe,

First off, you are awesome. Love your approach with this library.

Going through the code, I was curious why you are decoding comment text using CP437 encoding, I couldn't find a reference to this encoding in the PKWare spec. Should UTF8 just work fine?

**Comment by thejoshwolfe** [comment]
Here is the zip file spec I followed: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

And a quote from Appendix D:
> The ZIP format has historically supported only the original IBM PC character 
encoding set, commonly referred to as IBM Code Page 437.

The appendix goes on to explain how to specify UTF-8 encoding for the file names and comments of individual files. There is no zipfile-wide charset specification and no way I can find to specify the charset of the zipfile comment. My interpretation of this situation is that the zipfile comment is always the "default" encoding of CP437.

**Comment by kirkouimet** [comment]
Thanks for this thoughtful and comprehensive response, and thanks for all of your work on this project
