### ISSUE TITLE
ENOENT

### ISSUE THREAD

**Issue by foxpjustin** [thejoshwolfe/yauzl#20]
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open 'TestZip/001.png'

    at Error (native)

When running example script on any file I get this. I don't know if it's really an error, but I'm using the example script exactly as written changing only the path to my .zip file.

**Comment by thejoshwolfe** [comment]
It looks like `fs.createWriteStream()` is trying to create a file called `001.png` in a directory called `TestZip`, but the directory `TestZip` does not exist. I recommend using [path.dirname](https://nodejs.org/api/path.html#path_path_dirname_p) and either [fs.mkdir](https://nodejs.org/api/fs.html#fs_fs_mkdir_path_mode_callback) or possibly a "mkdirp"-like utility function from an npm module to create the directory for each entry before trying to extract it.

Really, the example code in the README needs this functionality to be complete, but it's a bit complicated and not directly relevant to this library. For that reason, I just left in the comment `// ensure parent directory exists, and then:` instead of actually providing code that does that.

**Comment by foxpjustin** [comment]
OK I've found and applied some code to test for and create the folder.
// http://stackoverflow.com/questions/21194934/node-how-to-create-a-directory-if-doesnt-exist

As I have it written now, I get my folder, and I get two useless .png files (my testzip has 5 png's in a folder) along with this message in the console:
All of the winning. 
All of the winning.
Error from inside ensureExists function. Error: ENOENT, mkdir '/Volumes/PrePress/Tiffs/Artists_DS/JUSTINS TIFFS/NODE/TestFolder/__MACOSX/TestZip'
Error from inside ensureExists function. Error: ENOENT, mkdir '/Volumes/PrePress/Tiffs/Artists_DS/JUSTINS TIFFS/NODE/TestFolder/__MACOSX/TestZip'
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '__MACOSX/TestZip/._001.png'
    at Error (native)

The "__MACOSX" doesn't exist anywhere and isn't being asked for. Here is the code as I have it written.

var yauzl = require('yauzl');
var fs = require('fs');
var path = require('path');
var EventEmitter = require('events').EventEmitter;
var filesEE = new EventEmitter();

yauzl.open('**Replace with path to zip file**.TestZip.zip', function(err, zipfile) {
	if (err) throw err;
	zipfile.on("entry", function(entry) {
		if (/\/$/.test(entry.fileName)) {
			// directory file names end with '/'
			return;
		}
		zipfile.openReadStream(entry, function(err, readStream) {
			if (err) throw err;
			// ensure parent directory exists, and then:

			var currentEntry = path.dirname(entry.fileName);
			var cPath = path.normalize('**Replace with path to folder**');
			ensureExists(cPath + currentEntry, 0744, function(err) {
				if (err){ // handle folder creation error
					console.log('Error from inside ensureExists function. ' + err);
				}
				else { // we're all good
					console.log('All of the winning.');
					filesEE.emit('files_ready'); // trigger files_ready event
				}
			});
			// ensure parent directory exists, and then:
			
			filesEE.on('files_ready',function(){
				readStream.pipe(fs.createWriteStream(entry.fileName));
			});
		});
	});
});

// http://stackoverflow.com/questions/21194934/node-how-to-create-a-directory-if-doesnt-exist
function ensureExists(where, mask, cb) {
	if (typeof mask === 'function') { // allow the `mask` parameter to be optional
		cb = mask;
		mask = 0777;
	}
	fs.mkdir(where, mask, function(err) {
		if (err) {
			if (err.code === 'EEXIST') cb(null); // ignore the error if the folder already exists
			else cb(err); // something else went wrong
		} else cb(null); // successfully created folder
	});
}

**Comment by thejoshwolfe** [comment]
I think that this is now outside the scope of yauzl support, but I'll try to keep helping as best I can. My suspicion is that the zipfile is asking you to create a file that's at least 2 directories deep in the file system, for example `a/b/c.txt`. Your code looks like it will try to create the directory `a/b`, but the problem is that not even `a` exists yet. I think you need something more like an "mkdirp" solution rather than a "mkdir" solution.

consider something like this module: https://www.npmjs.com/package/mkdirp

**Comment by foxpjustin** [comment]
I am getting the same result with "mkdirp"

pow!
pow!
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '__MACOSX/TestZip/._001.png'
    at Error (native)

Here is my code:

var yauzl = require('yauzl');
var fs = require('fs');
var path = require('path');
var mkdirp = require('mkdirp');
var EventEmitter = require('events').EventEmitter;
var filesEE = new EventEmitter();

yauzl.open('/Volumes/PrePress/Tiffs/Artists_DS/JUSTINS\ TIFFS/NODE/TestFolder/TestZip.zip', function(err, zipfile) {
	if (err) throw err;
	zipfile.on("entry", function(entry) {
		if (/\/$/.test(entry.fileName)) {
			// directory file names end with '/'
			return;
		}
		zipfile.openReadStream(entry, function(err, readStream) {
			if (err) throw err;
			// ensure parent directory exists, and then:

			var currentEntry = path.dirname(entry.fileName);
			var cPath = path.normalize('/Volumes/PrePress/Tiffs/Artists_DS/JUSTINS\ TIFFS/NODE/TestFolder/');
			mkdirp (cPath + currentEntry, function (err) {
				if (err) console.error('Error from inside mkdirp function. ' + err);
				else console.log('pow!')
				filesEE.emit('files_ready'); // trigger files_ready event
			});

			// ensure parent directory exists, and then:
			
			filesEE.on('files_ready',function(){
				readStream.pipe(fs.createWriteStream(entry.fileName));
			});
		});
	});
});

Here is what the contents of my .zip file look like:
![screen shot 2015-08-07 at 12 45 03 pm](https://cloud.githubusercontent.com/assets/13522145/9141942/2ae38712-3d02-11e5-82f0-8ce5506d5842.png)

This is what I'm getting:
![screen shot 2015-08-07 at 12 45 42 pm](https://cloud.githubusercontent.com/assets/13522145/9141954/3bf2ef3e-3d02-11e5-83ab-7ceb790fe302.png)
These files will not open in photoshop. They show zero bytes.

If the problem is with my code/implementation, let me know and I'll seek advice elsewhere.

**Comment by thejoshwolfe** [comment]
Can I get the zipfile from you? I'd like to take a loot and see if there's anything strange about the metadata.

**Comment by foxpjustin** [comment]
https://drive.google.com/file/d/0BzEoJSYDhH_WN3Zydkpqdy1MSm8/view?usp=sharing

**Comment by thejoshwolfe** [comment]
Interesting. There is indeed metadata for a __MACOSX folder in your zipfile. It seems that many zipfile viewers hide this folder, but it really is there in the zipfile:

```
$ unzip -l TestZip.zip 
Archive:  TestZip.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2015-08-04 10:37   TestZip/
    19946  2015-08-04 10:35   TestZip/001.png
        0  2015-08-04 10:37   __MACOSX/
        0  2015-08-04 10:37   __MACOSX/TestZip/
      120  2015-08-04 10:35   __MACOSX/TestZip/._001.png
    20711  2015-08-04 10:35   TestZip/002.png
      120  2015-08-04 10:35   __MACOSX/TestZip/._002.png
    25217  2015-08-04 10:36   TestZip/003.png
      120  2015-08-04 10:36   __MACOSX/TestZip/._003.png
    21366  2015-08-04 10:36   TestZip/004.png
      120  2015-08-04 10:36   __MACOSX/TestZip/._004.png
    22202  2015-08-04 10:37   TestZip/005.png
      120  2015-08-04 10:37   __MACOSX/TestZip/._005.png
---------                     -------
   110042                     13 files
```

According to http://superuser.com/a/364124/87555 , this is an example of https://en.wikipedia.org/wiki/Resource_fork . I've learned something today about Mac that I didn't previously know. Cool.

However, I think I found the problem with your code, which is not related to Mac or yauzl. I was able to get your code to work by changing the way you're dealing with paths. You're calling `mkdirp()` with an absolute path that seems to be relative to the zipfile, but then you're calling `fs.createWriteStream()` with a path relative to the current working directory. I believe that is the source of your ENOENT errors.

Regarding the 0-byte files, I think that's just an issue with the process terminating abruptly before it had a chance to pump the file data into the newly created files. I think fixing the ENOENT will fix the 0-byte files as well.

**Comment by foxpjustin** [comment]
I changed fs.createWriteStream() to an absolute path, and it was still behaving the same way on my system. That was a great catch and I appreciate it but it didn't solve it for me. The __MACOSX files seem to be the problem. I've got it completing without an error by instructing it to skip anything that starts with "__MACOSX". My solution for skipping uses a prototype of String because I'm lousy at regex.

However the first 3 files are 0 KB, the fourth is 21KB which seems about right but it still won't open, and the fifth is a nice healthy file just as I expected it at 22 KB that opens and makes us all so happy. 

I'm wondering if I need to add more event listeners to keep it from completing before the files are ready?

Here is my code:
var yauzl = require('yauzl');
var fs = require('fs');
var path = require('path');
var mkdirp = require('mkdirp');
var EventEmitter = require('events').EventEmitter;
var filesEE = new EventEmitter();

yauzl.open('/Volumes/PrePress/Tiffs/Artists_DS/JUSTINS\ TIFFS/NODE/TestFolder/TestZip.zip', function(err, zipfile) {
	if (err) throw err;
	zipfile.on("entry", function(entry) {
		if (/\/$/.test(entry.fileName)) {
			// directory file names end with '/'
			return;
		}
		if (entry.fileName.startsWith('__MACOSX') ){
			return;
		}
		zipfile.openReadStream(entry, function(err, readStream) {
			if (err) throw err;
			// ensure parent directory exists, and then:

			var currentEntry = path.dirname(entry.fileName);
			var cPath = path.normalize('/Volumes/PrePress/Tiffs/Artists_DS/JUSTINS\ TIFFS/NODE/TestFolder/');
			mkdirp (cPath + currentEntry, function (err) {
				if (err) console.error('Error from inside mkdirp function. ' + err);
				else console.log('pow!')
				filesEE.emit('files_ready'); // trigger files_ready event
			});

			// ensure parent directory exists, and then:
			
			filesEE.on('files_ready',function(){
				readStream.pipe(fs.createWriteStream('/Volumes/PrePress/Tiffs/Artists_DS/JUSTINS\ TIFFS/NODE/TestFolder/' + entry.fileName));
			});
		});
	});
});

if (typeof String.prototype.startsWith != 'function') {
  String.prototype.startsWith = function (str){
    return this.slice(0, str.length) == str;
  };
}

**Comment by thejoshwolfe** [comment]
I think it's a pretty safe bet that the problem is not with yauzl at this point. Asynchronous programming in node can be complicated, and I remember having these sorts of problems myself when I was still learning how all these paradigms were supposed to work.

I don't really have a recommendation for what to try at this point, because I don't want to write your code for you. You're on your own. Good luck.
