### ISSUE TITLE
Invalid central directory file header signature

### ISSUE THREAD

**Issue by asaf050** [thejoshwolfe/yauzl#30]
Hey,
I can't find any node package that handles compressed zip files...
Same error as
https://github.com/glebdmitriew/node-unzip-2/issues/1

**Comment by thejoshwolfe** [comment]
please provide an example zip file that gives this error. I'd be happy to look into it (however my schedule for the next few days might be busy).

**Comment by thejoshwolfe** [comment]
> I can't find any node package that handles compressed zip files...

yauzl handles compressed zip files. it is being used by [thousands](https://www.npmjs.com/package/yauzl) of users every day. if you've found a bug, i would certainly like to know about it, so it can be fixed.

**Comment by asaf050** [comment]
@thejoshwolfe  I'm sorry for the late respond. Thanks
[Holmatro Spreader Assembly_1.zip](https://github.com/thejoshwolfe/yauzl/files/288320/Holmatro.Spreader.Assembly_1.zip)

**Comment by thejoshwolfe** [comment]
your zip file is broken. the 3 bytes `53 4D 47` a.k.a. `"SMG"` seem to have been prepended to the file, which is throwing off all the offsets in the metadata. For example, the End of Central Directory Record says the first Central Directory Record begins at offset `0x2a004f`, when really it begins at `0x2a0052` (where you will find the bytes `50 4B 01 02`).

you can see a clue about this when you use InfoZip:

```
$ unzip -tq Holmatro.Spreader.Assembly_1.zip
warning [Holmatro.Spreader.Assembly_1.zip]:  3 extra bytes at beginning or within zipfile
  (attempting to process anyway)
No errors detected in compressed data of Holmatro.Spreader.Assembly_1.zip.
```

If I were the author of InfoZip, I would not have said "No errors detected" anywhere in the output of this command, because your zipfile is actually not conformant to the spec. InfoZip seems to have error-recovery mechanisms to guess what you meant, and carry on from there with confidence that they guessed correctly. yauzl makes no such presumptions, and does not attempt to anticipate these kinds of mistakes.

You can fix your zipfile with this command:

```
tail -c +4 Holmatro.Spreader.Assembly_1.zip > fixed.zip
```

**Comment by asaf050** [comment]
Hey @thejoshwolfe , when using unzip via terminal it decompressed successfully the file.
I want to fix/decompressed the file without any terminal code...

Do you know any solution?

**Comment by thejoshwolfe** [comment]
do you know why the zipfile is being corrupted? if you could solve that, it would bypass any need for a workaround afterward.

if not, you have a number of options in JavaScript to correct the offset alignments. one idea is to make a copy of the file excluding the first three bytes. you could do that with `fs.createReadStream()` piped to a filter you implement that skips the first 3 bytes, piped to an `fs.createWriteStream()`. another idea is to use `yauzl.fromRandomAccess()` and implement a reader that reports a size of 3 fewer bytes and translates all file offsets by +3.

out of curiosity, what is your usecase, if you don't mind my asking?

**Comment by asaf050** [comment]
@thejoshwolfe thank you for answering.

This zip file is an output of a software called Solidworks Composer. I can't fix that because this is the normal output. My app need to support those files.

I will look into the workarounds you suggested and will try to make it work.
Thanks you very much!

**Comment by thejoshwolfe** [comment]
does Solidworks Composer call the zip file a .sgm file? it might be informative for yauzl to provide example code that implements a RandomAccessReader that does the simple offset logic. currently, the only example of a RandomAccessReader is in test/test.js, which is not a very good example.

**Comment by asaf050** [comment]
Yes, the original file extension is smg. If it possible, I think it maybe good to create an AutomaticRandomAccessReader that read the file extension and implements the RandomAccessReader.

What do you think?

**Comment by andrewrk** [comment]
You're trying to read a non zip file with a zip file library. You can't expect that to work.

> I think it may be good to create an AutomaticRandomAccessReader that read the file extension and implements the RandomAccessReader in a seamless way.

It's not within the scope of yauzl to know what a "sgm" file is.

**Comment by asaf050** [comment]
@andrewrk Hey
I believe there is a reason why WinRAR and 7zip can open this file successfully. But the decision is yours :+1:

**Comment by thejoshwolfe** [comment]
I'm most of the way through implementing an example that reads a zipfile from the middle of a file. this sort of thing would be useful to parse a zipfile in-place that is embedded in some other container archive format. I'm adding it to the unzip.js example.

I still don't plan to have any automatic search for where the zipfile really begins, like InfoZip and apparently 7Zip and WinRAR have. but if you knew in advance that you were dealing with a .sgm file, you could do something like the way the example works to parse it correctly in-place. the important thing is that you tell yauzl where the zipfile really starts and stops. yauzl will not automatically go searching for it.

All of this that I'm talking about would go in the example only. I'm not planning to add any features to yauzl that don't already exist. What I'm talking about is using a custom RandomAccessReader, which is what you would have to do as a user of yauzl. the example code should be instructive enough to help you do whatever you need to do to parse .sgm or any other file format that contains an embedded zipfile.

**Comment by asaf050** [comment]
Ok,
Please let me know if you need anything else from me. :+1:

**Comment by thejoshwolfe** [comment]
@asaf050, let me know if that example gives you some insight into how to accomplish your goals. The `unzip.js` example has been enhanced with extra capabilities, so that now you can extract the files in your zipfile with this command:

```
$ node path/to/yauzl/examples/unzip.js Holmatro.Spreader.Assembly_1.zip --offset 3
```

**Comment by asaf050** [comment]
@thejoshwolfe Thank you. Works like a charm!
One last question, How can I set the destination path?

**Comment by thejoshwolfe** [comment]
Not sure if you're talking about the command line program, in which case you can't, or your application code that uses the yauzl library. In the latter case, yauzl doesn't do anything with the output except provide it to your code, so you can find calls to `fs.createWriteStream()` and possibly `fs.mkdir()` or the like in your own code to change to your liking. you might even be able to avoid writing the extracted files to disk entirely, depending on your usecase. in short, yauzl itself has no destination path.
