### ISSUE TITLE
How do I stop traversing but still have an end event fire?

### ISSUE THREAD

**Issue by jeacott1** [thejoshwolfe/yauzl#44]
How do I stop traversing the zip but still have the zip 'end' event fire?
it seems that zipfile.readEntry() is the only thing that invokes the zip.end event,
 but i dont want to call it when I have what I want, and I DO want the end event to be called.

autoClose: false doesnt help. teh close method doesnt fire for fromBuffer. 
what am I missing?

```
var yauzl = require("yauzl");
var fs = require("fs");
var path = require("path");
var mkdirp = require("mkdirp"); // or similar

 yauzl.fromBuffer(buffer,{lazyEntries: true}, function(err, zip) {
  if (err) throw err;
  zipfile.readEntry();
  zipfile.on("entry", function(entry) {
    if (/\/$/.test(entry.fileName)) {
        //do something here then stop walking the zip file.
   
    } else {
     zipfile.readEntry();
    }
  });

    zip.once("end", function() {
     //clean up. this never fires if we found our target file.
    });

});




```

**Comment by thejoshwolfe** [comment]
What about just calling your own end handler directly?

```js
var yauzl = require("yauzl");
var fs = require("fs");
var path = require("path");
var mkdirp = require("mkdirp"); // or similar

yauzl.fromBuffer(buffer,{lazyEntries: true}, function(err, zip) {
  if (err) throw err;
  zipfile.readEntry();
  zipfile.on("entry", function(entry) {
    if (/\/$/.test(entry.fileName)) {
      // do something here.
      endHandler();
    } else {
      zipfile.readEntry();
    }
  });
  zip.once("end", endHandler);

  function endHandler() {
    //clean up.
  }
});
```

**Comment by jeacott1** [comment]
sure but feels like a hack. just wondered if there was something I was missing.

**Comment by thejoshwolfe** [comment]
If the ZipFile were managing an fd that you wanted to close, you should call `zipfile.close()` when you're done. (This works while you're partway through reading entries, as explained in the docs.)

But if the ZipFile is simply reading from a Buffer, then the only "resources" to clean up are heap allocations that need to be garbage collected. That happens by simply abandoning the objects, which is what you should do for your case.

The purpose of the `end` event is to inform you that no more `entry` events will be emitted. If you're not interested in any `entry` events anyway, then an `end` event shouldn't interest you either.

The `autoClose` option really just (effectively) calls `close()` in response to the `end()` event. All `close()` does is tell yauzl that you promise not to open any more read streams for entries. Then yauzl keeps count of how many read streams are already open for entries, and once that number reaches 0, it closes the fd, if any, as explained above. The only purpose of `close()` is to (eventually) close any underlying fd that yauzl is managing.

Hope that helps explain the design a little better. I think directly calling your end handler is the right design and not a hack, if that helps you feel any better.
