### ISSUE TITLE
Concat shredded file content strings by default?

### ISSUE THREAD

**Issue by kunokdev** [thejoshwolfe/yauzl#56]
```
  zipfile.on("entry", function(entry) {
          if (/\/$/.exec(entry)) return;
          zipfile.openReadStream(entry, options, function(err, readStream) {
            if (err) throw err;
            readStream.on('data', data => {
              console.log(entry.fileName) 
              console.log(data.toString())
            })
           })
          zipfile.readEntry()
        });
```

I am extracting xml files from zip and when I log them inside `on('data'` event they are multiparted. Basically in logs, fileName gets repeated and data is shredded in parts.

Is there builtin method for concating this data as single strings that are ready to be parsed as whole?

**Comment by thejoshwolfe** [comment]
There's no builtin method I'm aware of, but I use `bl` in yauzl's test system for collecting a `Readble` stream into a `Buffer`. However, you may want to just stream the data into your logging mechanism.

Something like this (for stdout):

```js
zipfile.on("entry", function(entry) {
  if (/\/$/.exec(entry)) return;
  zipfile.openReadStream(entry, options, function(err, readStream) {
    if (err) throw err;
    console.log(entry.fileName);
    readStream.pipe(process.stdout);
    readStream.on("end"), function() {
      zipfile.readEntry();
    });
   });
});
```
