### ISSUE TITLE
Create 2 options to decodeStrings without validateFileName

### ISSUE THREAD

**Issue by FabriceGaudin** [thejoshwolfe/yauzl#66]
Thank you for this lib, it works great !
In my use case, i'd like to ignore the "invalid characters in fileName" errors, to automatically convert backslashes to forward slashes.
I read that @thejoshwolfe recommands using `decodeStrings: false` here: https://github.com/thejoshwolfe/yauzl/issues/54#issuecomment-287585919
But as he mentions it:
> You'll have to do some extra work to do UTF-8 vs CP437 decoding

It's too bad to do this extra work whereas the lib can do it, and this work isn't directly linked to the validation step. I'd like to create 2 different options:
- `autoValidateFileName`: default true, if false, the method `validateFileName` isn't called
- `decodeStrings`: default true, if false, don't decode Buffer.

Or if my use case is not so specific, maybe we can add an option `authorizeBackslash` to avoid throwing an error in [validateFileName](https://github.com/thejoshwolfe/yauzl/blob/master/index.js#L599).

What do you think about it ?

**Comment by thejoshwolfe** [comment]
Can you tell me what zipfile creator is putting backslash characters in filenames? I'd be much more willing to support that non-standard usecase if I can reproduce the problem.

**Comment by FabriceGaudin** [comment]
@thejoshwolfe Unfortunately I don't know which zipfile creators are used. It seems that my users are getting zip files from a third party.

**Comment by thejoshwolfe** [comment]
thanks to @YanBeat in #88 for verifying that .NET 4.5 is indeed the culprit. Expect a fix for this issue coming soon.

**Comment by thejoshwolfe** [comment]
published yauzl 2.10.0 which replaces backslashes by default. let me know if this solves your problem.
