### ISSUE TITLE
Add .npmignore with .travis.yml

### ISSUE THREAD

**Issue by tomap** [thejoshwolfe/yauzl#67]
Hi,

Could you add a .npmignore file with .travis.yml to produce a cleaner npm package ?

Thank you

**Comment by thejoshwolfe** [comment]
The latest published version of of yauzl 2.9.1 contains only these files:

* `index.js`
* `LICENSE`
* `package.json`
* `README.md`

yauzl's `package.json` contains `"files": [ "index.js" ]` using the "whitelist" approach so an `.npmignore` "blacklist" is not necessary.
