### ISSUE TITLE
how convert readstream to buffer

### ISSUE THREAD

**Issue by unsilence** [thejoshwolfe/yauzl#71]
zipfile.openReadStream(entry, function(err, readStream) {
        if (err) throw err;
        readStream.on("end", function() {
          zipfile.readEntry();
        });
        readStream.pipe(somewhere);
      });
}

how convert readStream to buffer ?

**Comment by thejoshwolfe** [comment]
There are a number of ways to do this. I've used [bl](https://www.npmjs.com/package/bl) before. Or you can just do this: https://github.com/thejoshwolfe/yauzl/blob/7d619bf4e498d0bc9164f8644cb8df18727ce98b/test/test.js#L115-L120

**Comment by unsilence** [comment]
I've settled it, thank you for your patience
