### ISSUE TITLE
Unable to extract APK

### ISSUE THREAD

**Issue by farhantariq92** [thejoshwolfe/yauzl#91]
I am trying to extract following APK: 
https://drive.google.com/open?id=1trk6nvcX6aS8tYFfro7cLcUw2EbQc7VB

but it errors out with following exception: 
‘Error: absolute path: /deviceinsight-collector-javascript-6.5.0-9.pom’.

I have debugged the code and found at following line# 251 of the index.js file (version "yauzl@2.10.0"), when extracting a chunk from buffer:

code snippet #1

```
var buffer = newBuffer(46);
readAndAssertNoEof(self.reader, buffer, 0, buffer.length, self.readEntryCursor, function(err) {
.....
entry.fileNameLength = buffer.readUInt16LE(28);

```

the above lines of code give the length of ‘AndroidManifest.xml’ file in entry.fileNameLength
and after the code snippet #2 reads the buffer and sends back the string ‘AndroidManifest.xml’ in entry.fileName.

code snippet #2

```
readAndAssertNoEof(self.reader, buffer, 0, buffer.length, self.readEntryCursor, function(err) {
    if (err) return emitErrorAndAutoClose(self, err);
    if (self.emittedError) return;
    var isUtf8 = (entry.generalPurposeBitFlag & 0x800) !== 0;
     .....
    entry.fileName = self.decodeStrings ? decodeBuffer(buffer, 0, entry.fileNameLength, isUtf8)
                                        : buffer.slice(0, entry.fileNameLength);

```

the above code works fine on older version of the same app 
(https://drive.google.com/open?id=1tEksPfQsW6wJRqC-1pFDRrec0CoyOxYc)

code snippet #3

```
entry.fileName = self.decodeStrings ? decodeBuffer(buffer, 0, entry.fileNameLength, isUtf8)
                                        : buffer.slice(0, entry.fileNameLength);
```

we are getting the string ‘/deviceinsight-collector-javascript-6.5.0-9.pom’ in entry.fileName and after that code snippet #4 actually causes the validation failure.

code snippet #4

```
var errorMessage = validateFileName(entry.fileName, self.validateFileNameOptions);
if (errorMessage != null) return emitErrorAndAutoClose(self, new Error(errorMessage));

...

function validateFileName(fileName) {
    if (fileName.indexOf(“\\“) !== -1) {
       return “invalid characters in fileName: ” + fileName;
   }
  if (/^[a-zA-Z]:/.test(fileName) || /^\//.test(fileName)) {
      return “absolute path: ” + fileName;
  }
  if (fileName.split(“/”).indexOf(“..“) !== -1) {
     return “invalid relative path: ” + fileName;
  }
  // all good
  return null;
}
```

I hope this will help in finding the root cause of this issue.

**Comment by aziz-shafique** [comment]
thanks a lot @thejoshwolfe. We have fixed the APK and it is now extracted successfully.

**Comment by thejoshwolfe** [comment]
Great! Please reopen if you have any further questions.
