### ISSUE TITLE
Another `Error: invalid central directory file header signature`

### ISSUE THREAD

**Issue by hellatan** [thejoshwolfe/yauzl#98]
I've been trying to make sense of this issue that just occurred for us but I'm really not sure what is going on. From what I've gathered thus far, `yauzl` is supposed to handle zip files. However, it seems like it's trying to parse a directory with the error i'm seeing:
```
11:08:10 Directory: /jenkins/workspace/pullrequest/node_modules/puppeteer
11:08:10 Output:
11:08:10 events.js:183
11:08:10       throw er; // Unhandled 'error' event
11:08:10       ^
11:08:10 
11:08:10 Error: invalid central directory file header signature: 0x4f994400
11:08:10     at /jenkins/workspace/pullrequest/node_modules/yauzl/index.js:231:70
11:08:10     at /jenkins/workspace/pullrequest/node_modules/yauzl/index.js:473:5
11:08:10     at /jenkins/workspace/pullrequest/node_modules/fd-slicer/index.js:32:7
11:08:10     at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)
```
I tried to replicate this locally (mac 10.12.6) but this error does not get thrown. It looks like we're running CentOS 7 on our build servers, where this error is being thrown. 

Thoughts on where/how else to troubleshoot?

**Comment by thejoshwolfe** [comment]
To avoid crashing, see the section "How to Avoid Crashing" in yauzl's readme. You probably need to register an error handler on a read stream somewhere.

Hopefully that will help debug why there's what appears to be a malformed zipfile somewhere in the system.

**Comment by thejoshwolfe** [comment]
I know that the Mac Archive Utility creates malformed zipfiles that I've got a long-running project to work around. See #60 for one of the many issues in this repo relating to this issue.

Is your zipfile larger than 4GB or does it contain any files that are over 4GB or does it contain over 65534 files? If so, then I'm confident that that's the issue.
