### ISSUE TITLE
Extracting rars, tars, tar.gz etc...

### ISSUE THREAD

**Issue by macmichael01** [thejoshwolfe/yauzl#99]
I just stumbled upon this library and haven't had the chance to dig through the source. Is it possible to extract Rars, tars, and other non-zip formats?

**Comment by thejoshwolfe** [comment]
yauzl is just a zipfile reader. If you'd like to make a multi-format archive reader, I suggest using yauzl as the zipfile backend. (Perhaps a multi-archive tool has already been made somewhere that does this.)
